#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --partition=clara-job
#SBATCH --mem-per-cpu=4G
#SBATCH --gres=gpu:v100:1
#SBATCH --job-name=sporttaskme22
#SBATCH -o ./working_folder/slurm_logs/slurm_log.%a.out # STDOUT

module purge
module load matplotlib
module load scikit-learn
module load torchvision
module load PyTorch/1.10.0-foss-2021a-CUDA-11.3.1
#module load PyTorch/1.9.0-fosscuda-2020b
module load OpenCV/4.5.5-foss-2021b-contrib

srun python main.py