#!/bin/bash -l 
#SBATCH --ntasks=1
#SBATCH --time=72:00:00
#SBATCH --partition=clara-job
#SBATCH --gres=gpu:v100:1
#SBATCH --mem-per-gpu=5140
#SBATCH --job-name=Sporttaskme22
#SBATCH -o GIT/SportTaskME22/working_folder/slurm_logs/R-%x.%j.out
#SBATCH -e GIT/SportTaskME22/working_folder/slurm_logs/R-%x.%j.err

cd GIT/SportTaskME22/

module load Anaconda3
conda activate open-mmlab

srun python main_1.py c s notest